# -*- coding: utf-8 -*-
"""Panda_Normal_Use_Of_DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14POps7NMku8W7Rd9Cu8eotVrCJo-V290

Import Panda
"""

import pandas as pd

"""# Creating DataFrame Using Python Dictionary"""

data={
'name':["Ridwanul","Basit"],
'age': [24,25]

}
df=pd.DataFrame(data)
print(df)

weather_data={
    "Day" : ["1/01/2025","10/01/2025","20/01/2025","31/01/2025","10/02/2025","20/02/2025"],
    "Temperature" : [10,12,11,15,13,20],
    "Windspeed" : [3,1,5,4,2,7],
    "Event" : ["Snow","Rain","Snow","Sunny","Sunny","Hot"]
}
df=pd.DataFrame(weather_data)

"""# Printing DataFrame"""

df     #  df==print(df)

df[:]

"""# Work with row column"""

df.shape   # printed the size of row and column   (row,column)

df.head ()  # it basically  print first few row minimum 5 from all

df.tail()    # it basically print few row minimum 5 from all from the last

df.head(3)    # printed first 3 rows

df.tail(2)    # printed from the last 2 row

df[2:4]    # print rows between 2 to 4 ( start, end) and end row is n-1

df.columns    # printed the all columns of the first row

df.Day     # printed all columns of day with index which stared from zero we can also call it by df["Day"]

df["Day"]

df[["Day","Temperature"]]    # printed specific column data

df["Temperature"].max()   # printed the max value of a column

df.describe()    # printed all types value

"""# Some Advance similar with SQl"""

df[df.Temperature>=13]    # printed those temperature which are equal or greather then 13

df[df.Temperature==df["Temperature"].max()]      # Printed the max temperature's column

df[["Day","Event"]][df.Temperature==df["Temperature"].max()]   # Printed the max temperature's specific column

df.set_index("Day", inplace=True)    # index will be out and index will set according to Day and give a data frame

df

df.reset_index(inplace=True)   # It will reset the actual DataFrame nd index will come again

df